export const guests = [
  {
    fullname: "Jonas Schmedtmann",
    email: "hello@jonas.io",
    nationality: "Portugal",
    nationalID: "3525436345",
    countryFlag: "https://flagcdn.com/pt.svg",
  },
  {
    fullname: "Jonathan Smith",
    email: "johnsmith@test.eu",
    nationality: "Great Britain",
    nationalID: "4534593454",
    countryFlag: "https://flagcdn.com/gb.svg",
  },
  {
    fullname: "Jonatan Johansson",
    email: "jonatan@example.com",
    nationality: "Finland",
    nationalID: "9374074454",
    countryFlag: "https://flagcdn.com/fi.svg",
  },
  {
    fullname: "Jonas Mueller",
    email: "jonas@example.eu",
    nationality: "Germany",
    nationalID: "1233212288",
    countryFlag: "https://flagcdn.com/de.svg",
  },
  {
    fullname: "Jonas Anderson",
    email: "anderson@example.com",
    nationality: "Bolivia (Plurinational State of)",
    nationalID: "0988520146",
    countryFlag: "https://flagcdn.com/bo.svg",
  },
  {
    fullname: "Jonathan Williams",
    email: "jowi@gmail.com",
    nationality: "United States of America",
    nationalID: "633678543",
    countryFlag: "https://flagcdn.com/us.svg",
  },

  // GPT
  {
    fullname: "Emma Watson",
    email: "emma@gmail.com",
    nationality: "United Kingdom",
    nationalID: "1234578901",
    countryFlag: "https://flagcdn.com/gb.svg",
  },
  {
    fullname: "Mohammed Ali",
    email: "mohammedali@yahoo.com",
    nationality: "Egypt",
    nationalID: "987543210",
    countryFlag: "https://flagcdn.com/eg.svg",
  },
  {
    fullname: "Maria Rodriguez",
    email: "maria@gmail.com",
    nationality: "Spain",
    nationalID: "1098765321",
    countryFlag: "https://flagcdn.com/es.svg",
  },
  {
    fullname: "Li Mei",
    email: "li.mei@hotmail.com",
    nationality: "China",
    nationalID: "102934756",
    countryFlag: "https://flagcdn.com/cn.svg",
  },
  {
    fullname: "Khadija Ahmed",
    email: "khadija@gmail.com",
    nationality: "Sudan",
    nationalID: "1023457890",
    countryFlag: "https://flagcdn.com/sd.svg",
  },
  {
    fullname: "Gabriel Silva",
    email: "gabriel@gmail.com",
    nationality: "Brazil",
    nationalID: "109283465",
    countryFlag: "https://flagcdn.com/br.svg",
  },
  {
    fullname: "Maria Gomez",
    email: "maria@example.com",
    nationality: "Mexico",
    nationalID: "108765421",
    countryFlag: "https://flagcdn.com/mx.svg",
  },
  {
    fullname: "Ahmed Hassan",
    email: "ahmed@gmail.com",
    nationality: "Egypt",
    nationalID: "1077777777",
    countryFlag: "https://flagcdn.com/eg.svg",
  },
  {
    fullname: "John Doe",
    email: "johndoe@gmail.com",
    nationality: "United States",
    nationalID: "3245908744",
    countryFlag: "https://flagcdn.com/us.svg",
  },
  {
    fullname: "Fatima Ahmed",
    email: "fatima@example.com",
    nationality: "Pakistan",
    nationalID: "1089999363",
    countryFlag: "https://flagcdn.com/pk.svg",
  },
  {
    fullname: "David Smith",
    email: "david@gmail.com",
    nationality: "Australia",
    nationalID: "44450960283",
    countryFlag: "https://flagcdn.com/au.svg",
  },
  {
    fullname: "Marie Dupont",
    email: "marie@gmail.com",
    nationality: "France",
    nationalID: "06934233728",
    countryFlag: "https://flagcdn.com/fr.svg",
  },
  {
    fullname: "Ramesh Patel",
    email: "ramesh@gmail.com",
    nationality: "India",
    nationalID: "9875412303",
    countryFlag: "https://flagcdn.com/in.svg",
  },
  {
    fullname: "Fatimah Al-Sayed",
    email: "fatimah@gmail.com",
    nationality: "Kuwait",
    nationalID: "0123456789",
    countryFlag: "https://flagcdn.com/kw.svg",
  },
  {
    fullname: "Nina Williams",
    email: "nina@hotmail.com",
    nationality: "South Africa",
    nationalID: "2345678901",
    countryFlag: "https://flagcdn.com/za.svg",
  },
  {
    fullname: "Taro Tanaka",
    email: "taro@gmail.com",
    nationality: "Japan",
    nationalID: "3456789012",
    countryFlag: "https://flagcdn.com/jp.svg",
  },
  {
    fullname: "Abdul Rahman",
    email: "abdul@gmail.com",
    nationality: "Saudi Arabia",
    nationalID: "4567890123",
    countryFlag: "https://flagcdn.com/sa.svg",
  },
  {
    fullname: "Julie Nguyen",
    email: "julie@gmail.com",
    nationality: "Vietnam",
    nationalID: "5678901234",
    countryFlag: "https://flagcdn.com/vn.svg",
  },
  {
    fullname: "Sara Lee",
    email: "sara@gmail.com",
    nationality: "South Korea",
    nationalID: "6789012345",
    countryFlag: "https://flagcdn.com/kr.svg",
  },
  {
    fullname: "Carlos Gomez",
    email: "carlos@yahoo.com",
    nationality: "Colombia",
    nationalID: "7890123456",
    countryFlag: "https://flagcdn.com/co.svg",
  },
  {
    fullname: "Emma Brown",
    email: "emma@gmail.com",
    nationality: "Canada",
    nationalID: "8901234567",
    countryFlag: "https://flagcdn.com/ca.svg",
  },
  {
    fullname: "Juan Hernandez",
    email: "juan@yahoo.com",
    nationality: "Argentina",
    nationalID: "4343433333",
    countryFlag: "https://flagcdn.com/ar.svg",
  },
  {
    fullname: "Ibrahim Ahmed",
    email: "ibrahim@yahoo.com",
    nationality: "Nigeria",
    nationalID: "2345678009",
    countryFlag: "https://flagcdn.com/ng.svg",
  },
  {
    fullname: "Mei Chen",
    email: "mei@gmail.com",
    nationality: "Taiwan",
    nationalID: "3456117890",
    countryFlag: "https://flagcdn.com/tw.svg",
  },
];
